[2020-12-11 00:14:49,957] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T01:15:00+00:00 [queued]>
[2020-12-11 00:14:50,000] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T01:15:00+00:00 [queued]>
[2020-12-11 00:14:50,004] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 00:14:50,006] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2020-12-11 00:14:50,007] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 00:14:50,039] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Importar1> on 2020-12-10T01:15:00+00:00
[2020-12-11 00:14:50,053] {standard_task_runner.py:54} INFO - Started process 586 to run task
[2020-12-11 00:14:50,091] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'import-dag', 'Importar1', '2020-12-10T01:15:00+00:00', '--job_id', '23', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/import-dag.py', '--cfg_path', '/tmp/tmpl519s2wm']
[2020-12-11 00:14:50,099] {standard_task_runner.py:78} INFO - Job 23: Subtask Importar1
[2020-12-11 00:14:50,208] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: import-dag.Importar1 2020-12-10T01:15:00+00:00 [running]> 7d635893eab6
[2020-12-11 00:14:50,236] {import-dag.py:28} INFO - =====Ejecutando Tarea de Importacion =============
[2020-12-11 00:14:50,237] {import-dag.py:29} INFO - ===== Archivo  =============
[2020-12-11 00:14:50,239] {import-dag.py:30} INFO - time_series_covid19_confirmed_global
[2020-12-11 00:14:50,243] {import-dag.py:31} INFO - ===== Tabla  =============
[2020-12-11 00:14:50,246] {taskinstance.py:1150} ERROR - 'tabla'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/import-dag.py", line 32, in importarCsv
    logger.info(kwargs['tabla'])
KeyError: 'tabla'
[2020-12-11 00:14:50,252] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=import-dag, task_id=Importar1, execution_date=20201210T011500, start_date=20201211T001449, end_date=20201211T001450
[2020-12-11 02:14:04,454] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T01:15:00+00:00 [queued]>
[2020-12-11 02:14:04,513] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T01:15:00+00:00 [queued]>
[2020-12-11 02:14:04,514] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 02:14:04,515] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2020-12-11 02:14:04,516] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 02:14:04,535] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Importar1> on 2020-12-10T01:15:00+00:00
[2020-12-11 02:14:04,539] {standard_task_runner.py:54} INFO - Started process 159 to run task
[2020-12-11 02:14:04,610] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'import-dag', 'Importar1', '2020-12-10T01:15:00+00:00', '--job_id', '91', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/import-dag.py', '--cfg_path', '/tmp/tmpntw6sps7']
[2020-12-11 02:14:04,614] {standard_task_runner.py:78} INFO - Job 91: Subtask Importar1
[2020-12-11 02:14:04,695] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: import-dag.Importar1 2020-12-10T01:15:00+00:00 [running]> 12e92ec9b790
[2020-12-11 02:14:04,737] {import-dag.py:29} INFO - =====Ejecutando Tarea de Importacion =============
[2020-12-11 02:14:04,738] {import-dag.py:30} INFO - ===== Archivo  =============
[2020-12-11 02:14:04,739] {import-dag.py:31} INFO - time_series_covid19_confirmed_global.csv
[2020-12-11 02:14:04,740] {import-dag.py:32} INFO - ===== Tabla  =============
[2020-12-11 02:14:04,741] {import-dag.py:33} INFO - time_series_covid19_confirmed_global
[2020-12-11 02:14:04,742] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-11 02:14:04,760] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=import-dag, task_id=Importar1, execution_date=20201210T011500, start_date=20201211T021404, end_date=20201211T021404
[2020-12-11 02:14:09,451] {local_task_job.py:102} INFO - Task exited with return code 0
