[2020-12-11 00:18:19,757] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-11T00:18:03.396947+00:00 [queued]>
[2020-12-11 00:18:19,793] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-11T00:18:03.396947+00:00 [queued]>
[2020-12-11 00:18:19,797] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 00:18:19,799] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2020-12-11 00:18:19,799] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 00:18:19,829] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Importar1> on 2020-12-11T00:18:03.396947+00:00
[2020-12-11 00:18:19,840] {standard_task_runner.py:54} INFO - Started process 81 to run task
[2020-12-11 00:18:19,903] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'import-dag', 'Importar1', '2020-12-11T00:18:03.396947+00:00', '--job_id', '27', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/import-dag.py', '--cfg_path', '/tmp/tmpjq12gwnj']
[2020-12-11 00:18:19,907] {standard_task_runner.py:78} INFO - Job 27: Subtask Importar1
[2020-12-11 00:18:19,980] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: import-dag.Importar1 2020-12-11T00:18:03.396947+00:00 [running]> 7d635893eab6
[2020-12-11 00:18:20,049] {import-dag.py:28} INFO - =====Ejecutando Tarea de Importacion =============
[2020-12-11 00:18:20,051] {import-dag.py:29} INFO - ===== Archivo  =============
[2020-12-11 00:18:20,052] {import-dag.py:30} INFO - time_series_covid19_confirmed_global
[2020-12-11 00:18:20,053] {import-dag.py:31} INFO - ===== Tabla  =============
[2020-12-11 00:18:20,055] {taskinstance.py:1150} ERROR - 'tabla'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/import-dag.py", line 32, in importarCsv
    logger.info(kwargs['tabla'])
KeyError: 'tabla'
[2020-12-11 00:18:20,067] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=import-dag, task_id=Importar1, execution_date=20201211T001803, start_date=20201211T001819, end_date=20201211T001820
[2020-12-11 00:18:24,691] {local_task_job.py:102} INFO - Task exited with return code 1
