[2020-12-11 02:31:15,383] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar3 2020-12-10T00:10:00+00:00 [queued]>
[2020-12-11 02:31:15,427] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar3 2020-12-10T00:10:00+00:00 [queued]>
[2020-12-11 02:31:15,428] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 02:31:15,429] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2020-12-11 02:31:15,430] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 02:31:15,443] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Importar3> on 2020-12-10T00:10:00+00:00
[2020-12-11 02:31:15,448] {standard_task_runner.py:54} INFO - Started process 1476 to run task
[2020-12-11 02:31:15,502] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'import-dag', 'Importar3', '2020-12-10T00:10:00+00:00', '--job_id', '107', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/import-dag.py', '--cfg_path', '/tmp/tmpp62oldrq']
[2020-12-11 02:31:15,505] {standard_task_runner.py:78} INFO - Job 107: Subtask Importar3
[2020-12-11 02:31:15,576] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: import-dag.Importar3 2020-12-10T00:10:00+00:00 [running]> 12e92ec9b790
[2020-12-11 02:31:15,623] {import-dag.py:31} INFO - =====Ejecutando Tarea de Importacion =============
[2020-12-11 02:31:15,624] {import-dag.py:32} INFO - ===== Archivo  =============
[2020-12-11 02:31:15,625] {import-dag.py:33} INFO - time_series_covid19_recovered_global.csv
[2020-12-11 02:31:15,626] {import-dag.py:34} INFO - ===== Tabla  =============
[2020-12-11 02:31:15,627] {import-dag.py:35} INFO - time_series_covid19_recovered_global
[2020-12-11 02:31:15,645] {taskinstance.py:1150} ERROR - 'Variable 127.0.0.1 does not exist'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/import-dag.py", line 37, in importarCsv
    host = Variable.get("127.0.0.1")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 117, in get
    raise KeyError('Variable {} does not exist'.format(key))
KeyError: 'Variable 127.0.0.1 does not exist'
[2020-12-11 02:31:15,650] {taskinstance.py:1194} INFO - Marking task as UP_FOR_RETRY. dag_id=import-dag, task_id=Importar3, execution_date=20201210T001000, start_date=20201211T023115, end_date=20201211T023115
[2020-12-11 02:31:20,330] {local_task_job.py:102} INFO - Task exited with return code 1
