[2020-12-11 04:40:27,426] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T22:50:00+00:00 [queued]>
[2020-12-11 04:40:27,508] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: import-dag.Importar1 2020-12-10T22:50:00+00:00 [queued]>
[2020-12-11 04:40:27,510] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 04:40:27,511] {taskinstance.py:881} INFO - Starting attempt 2 of 2
[2020-12-11 04:40:27,513] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-11 04:40:27,532] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Importar1> on 2020-12-10T22:50:00+00:00
[2020-12-11 04:40:27,537] {standard_task_runner.py:54} INFO - Started process 6294 to run task
[2020-12-11 04:40:27,576] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'import-dag', 'Importar1', '2020-12-10T22:50:00+00:00', '--job_id', '667', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/import-dag.py', '--cfg_path', '/tmp/tmp924t726m']
[2020-12-11 04:40:27,580] {standard_task_runner.py:78} INFO - Job 667: Subtask Importar1
[2020-12-11 04:40:27,662] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: import-dag.Importar1 2020-12-10T22:50:00+00:00 [running]> d31552e451f4
[2020-12-11 04:40:27,705] {import-dag.py:31} INFO - =====Ejecutando Tarea de Importacion =============
[2020-12-11 04:40:27,707] {import-dag.py:32} INFO - ===== Archivo  =============
[2020-12-11 04:40:27,709] {import-dag.py:33} INFO - time_series_covid19_confirmed_global.csv
[2020-12-11 04:40:27,711] {import-dag.py:34} INFO - ===== Tabla  =============
[2020-12-11 04:40:27,714] {import-dag.py:35} INFO - time_series_covid19_confirmed_global
[2020-12-11 04:40:27,734] {taskinstance.py:1150} ERROR - 'Variable 127.0.0.1 does not exist'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/import-dag.py", line 36, in importarCsv
    host = Variable.get("127.0.0.1")
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/variable.py", line 117, in get
    raise KeyError('Variable {} does not exist'.format(key))
KeyError: 'Variable 127.0.0.1 does not exist'
[2020-12-11 04:40:27,745] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=import-dag, task_id=Importar1, execution_date=20201210T225000, start_date=20201211T044027, end_date=20201211T044027
[2020-12-11 04:40:32,404] {local_task_job.py:102} INFO - Task exited with return code 1
